# Generated by Django 5.1.3 on 2024-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phoneNumber", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("messageAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
