export enum ApiUrls {
  AUTH_LOGIN = "/auth/login",
  AUTH_ME = "/auth/me",
  HOME_STATS = "/home/stats",
  HOME_FEATURED_PROJECTS = "/home/featured-projects",
  HOME_EXPERIENCE = "/home/experience",
  HOME_SKILLS = "/home/skills",
  HOME_BLOG_PREVIEW = "/home/blog-preview",
  HOME_TICKER = "/home/ticker",
  ABOUT = "/about",
  ABOUT_EDUCATION = "/about/education",
  ABOUT_FACTS = "/about/facts",
  PROJECTS_LIST = "/projects",
  PROJECT_DETAIL = "/projects/:id",
  BLOG_POSTS = "/blog",
  BLOG_POST_DETAIL = "/blog/:id",
  BLOG_FEATURED = "/blog/featured",
  RESUME = "/resume",
  CONTACT_LINKS = "/contact/links",
  CONTACT_SUBMIT = "/contact/submit",
}
