export enum ApiUrls {
  HOME_STATS = "/api/home/stats",
  HOME_FEATURED_PROJECTS = "/api/home/featured-projects",
  HOME_EXPERIENCE = "/api/home/experience",
  HOME_SKILLS = "/api/home/skills",
  HOME_BLOG_PREVIEW = "/api/home/blog-preview",
  HOME_TICKER = "/api/home/ticker",
  ABOUT = "/api/about",
  ABOUT_EDUCATION = "/api/about/education",
  ABOUT_FACTS = "/api/about/facts",
  PROJECTS_LIST = "/api/projects",
  PROJECT_DETAIL = "/api/projects/:id",
  BLOG_POSTS = "/api/blog",
  BLOG_POST_DETAIL = "/api/blog/:id",
  BLOG_FEATURED = "/api/blog/featured",
  RESUME = "/api/resume",
  CONTACT_LINKS = "/api/contact/links",
  CONTACT_SUBMIT = "/api/contact/submit",
}
